# Generated by Django 4.2.26 on 2025-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('country_code', models.CharField(blank=True, max_length=10, verbose_name='Código do País')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Região/Estado')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Visitado em')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['-visited_at'],
            },
        ),
    ]
