# Generated by Django 4.2.26 on 2025-11-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_course_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_pt', models.CharField(default='Data Scientist', max_length=200, verbose_name='Cargo (PT)')),
                ('job_title_en', models.CharField(default='Data Scientist', max_length=200, verbose_name='Cargo (EN)')),
                ('job_title_es', models.CharField(default='Científico de Datos', max_length=200, verbose_name='Cargo (ES)')),
                ('slogan_pt', models.CharField(default='Transformando dados em insights', max_length=300, verbose_name='Slogan (PT)')),
                ('slogan_en', models.CharField(default='Transforming data into insights', max_length=300, verbose_name='Slogan (EN)')),
                ('slogan_es', models.CharField(default='Transformando datos en información', max_length=300, verbose_name='Slogan (ES)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto de Perfil')),
                ('about_pt', models.TextField(blank=True, help_text='Texto da seção sobre em português', verbose_name='Sobre (PT)')),
                ('about_en', models.TextField(blank=True, help_text='Texto da seção sobre em inglês', verbose_name='Sobre (EN)')),
                ('about_es', models.TextField(blank=True, help_text='Texto da seção sobre em espanhol', verbose_name='Sobre (ES)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
