# Generated by Django 4.2.26 on 2025-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_demo_video_project_repository_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, help_text='Separadas por vírgula', max_length=200, verbose_name='Tags'),
        ),
    ]
