# Generated by Django 4.2.26 on 2025-11-20 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-last_visit'], 'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_visit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Primeira Visita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Visita'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_count',
            field=models.IntegerField(default=1, verbose_name='Contagem de Visitas'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='Endereço IP'),
        ),
    ]
