# Generated by Django 4.2.26 on 2025-11-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_visitor_options_visitor_first_visit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Imagem de capa')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('upload', 'Vídeo Enviado')], default='youtube', max_length=10, verbose_name='Tipo de Vídeo')),
                ('youtube_url', models.URLField(blank=True, help_text='Ex: https://www.youtube.com/watch?v=VIDEO_ID', verbose_name='URL do YouTube')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Arquivo de Vídeo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('duration', models.CharField(blank=True, help_text='Ex: 15:30', max_length=20, verbose_name='Duração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='portfolio.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
