# Generated by Django 4.2.26 on 2025-11-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagem de capa da aula', null=True, upload_to='lessons/thumbnails/', verbose_name='Thumbnail da Aula'),
        ),
    ]
