# Generated by Django 4.2.26 on 2025-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_lesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'English'), ('es', 'Español')], default='pt', max_length=2, verbose_name='Idioma'),
        ),
    ]
