# Generated by Django 4.2.26 on 2025-11-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Vídeo curto de apresentação do projeto', null=True, upload_to='projects/videos/', verbose_name='Vídeo de Demonstração'),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.TextField(blank=True, help_text='Uma URL por linha', verbose_name='URLs dos Repositórios'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_explanation_url',
            field=models.URLField(blank=True, help_text='Link para vídeo explicativo no YouTube', verbose_name='URL de Explicação (YouTube)'),
        ),
    ]
